name: test
on:
  push:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v2
      - run: clang filtr_w_c.c
      - run: ./a.out < test.in
